version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: doctrine/dbal
    versions:
    - 3.1.0
  - dependency-name: facade/ignition
    versions:
    - 2.5.10
    - 2.6.0
    - 2.6.1
    - 2.7.0
    - 2.8.1
    - 2.8.2
  - dependency-name: friendsofphp/php-cs-fixer
    versions:
    - 2.18.3
    - 2.18.4
    - 2.18.5
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.3
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.35.1
  - dependency-name: css-loader
    versions:
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.1.4
    - 5.2.0
    - 5.2.1
    - 5.2.3
    - 5.2.4
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.11.0
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.6.0
    - 7.7.0
    - 7.8.0
    - 7.9.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
  - dependency-name: webpack-cli
    versions:
    - 4.5.0
    - 4.6.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.13
  - dependency-name: postcss-loader
    versions:
    - 5.1.0
